/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.Circuito;

/**
 *
 * @author julia
 */
public class Interfaz extends javax.swing.JFrame{
    
    Circuito varC = new Circuito();

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        SliderVoltaje.setEnabled(false);
        SliderResistencia.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOpciones = new javax.swing.JPanel();
        BotonIniciar = new javax.swing.JButton();
        SliderVoltaje = new javax.swing.JSlider();
        SliderResistencia = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelCircuito = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelOpciones.setBackground(new java.awt.Color(51, 51, 51));
        PanelOpciones.setForeground(new java.awt.Color(51, 51, 51));
        PanelOpciones.setMaximumSize(new java.awt.Dimension(720, 120));
        PanelOpciones.setMinimumSize(new java.awt.Dimension(720, 120));
        PanelOpciones.setPreferredSize(new java.awt.Dimension(720, 120));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonIniciar.setText("Iniciar Circuito");
        BotonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIniciarActionPerformed(evt);
            }
        });
        PanelOpciones.add(BotonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 86, -1, -1));

        SliderVoltaje.setMaximum(10);
        SliderVoltaje.setMinorTickSpacing(1);
        SliderVoltaje.setPaintLabels(true);
        SliderVoltaje.setPaintTicks(true);
        SliderVoltaje.setValue(0);
        SliderVoltaje.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderVoltajeStateChanged(evt);
            }
        });
        SliderVoltaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SliderVoltajeMouseReleased(evt);
            }
        });
        PanelOpciones.add(SliderVoltaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 18, -1, -1));

        SliderResistencia.setMinorTickSpacing(10);
        SliderResistencia.setPaintLabels(true);
        SliderResistencia.setPaintTicks(true);
        SliderResistencia.setValue(0);
        SliderResistencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderResistenciaStateChanged(evt);
            }
        });
        PanelOpciones.add(SliderResistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 18, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Voltaje de la Fuente");
        PanelOpciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 18, -1, 31));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nivel del Potenciometro");
        PanelOpciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 18, 120, 31));

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("0 v");
        PanelOpciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 55, -1, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("10 v");
        PanelOpciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 55, -1, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("1 kΩ");
        PanelOpciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("0 Ω");
        PanelOpciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        getContentPane().add(PanelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, -1));

        javax.swing.GroupLayout PanelCircuitoLayout = new javax.swing.GroupLayout(PanelCircuito);
        PanelCircuito.setLayout(PanelCircuitoLayout);
        PanelCircuitoLayout.setHorizontalGroup(
            PanelCircuitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        PanelCircuitoLayout.setVerticalGroup(
            PanelCircuitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(PanelCircuito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIniciarActionPerformed
        this.SliderVoltaje.setEnabled(true);
        this.SliderVoltaje.setValue(0);
        this.SliderResistencia.setValue(0);
        this.SliderResistencia.setEnabled(false);
        this.varC = new Circuito();
        this.varC.DibujarCircuito(this.PanelCircuito.getGraphics(), 160, 40);
        this.varC.DibujarInformacion(this.PanelCircuito.getGraphics(), 0, 40);
        this.varC.DibujarEstado(this.PanelCircuito.getGraphics(), 570, 100);
    }//GEN-LAST:event_BotonIniciarActionPerformed

    private void SliderVoltajeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderVoltajeStateChanged
        this.varC.EstadoNuevo(this.SliderVoltaje.getValue(), this.SliderResistencia.getValue());
        this.varC.DibujarCircuito(this.PanelCircuito.getGraphics(), 160, 40);
        this.varC.DibujarEstado(this.PanelCircuito.getGraphics(), 570, 100);
    }//GEN-LAST:event_SliderVoltajeStateChanged

    private void SliderResistenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderResistenciaStateChanged
        this.varC.EstadoNuevo(this.SliderVoltaje.getValue(), this.SliderResistencia.getValue());
        this.varC.DibujarCircuito(this.PanelCircuito.getGraphics(), 160, 40);
        this.varC.DibujarEstado(this.PanelCircuito.getGraphics(), 570, 100);
    }//GEN-LAST:event_SliderResistenciaStateChanged

    private void SliderVoltajeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SliderVoltajeMouseReleased
        this.SliderVoltaje.setEnabled(false);
        this.SliderResistencia.setEnabled(true);
        this.BotonIniciar.setText("Reiniciar Circuito");
    }//GEN-LAST:event_SliderVoltajeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIniciar;
    private javax.swing.JPanel PanelCircuito;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JSlider SliderResistencia;
    private javax.swing.JSlider SliderVoltaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
